name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Verify dependencies
      run: go mod verify

    - name: Build
      run: go build -v ./...

    - name: Run tests
      run: go test -v ./...

    - name: Create config
      run: |
        mkdir -p config
        cp config/config.yaml.example config/config.yaml

    - name: Create release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        mkdir -p release
        GOOS=linux GOARCH=amd64 go build -o release/bot-linux-amd64 cmd/bot/main.go
        GOOS=windows GOARCH=amd64 go build -o release/bot-windows-amd64.exe cmd/bot/main.go
        GOOS=darwin GOARCH=amd64 go build -o release/bot-darwin-amd64 cmd/bot/main.go

    - name: Upload artifacts
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: release/